# Generated by Django 2.1.4 on 2020-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='氏名')),
                ('email', models.CharField(max_length=255, verbose_name='E-Mail')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='age')),
            ],
        ),
    ]
